stages:
 - build
 - test
#  - package
#  - deploy

build-clio:
  stage: build
  image: legleux/clio_builder
  script: ./build_clio.sh
  artifacts:
    paths:
      - clio_src/build/
  tags:
    - 4xlarge

test-clio:
  stage: test
  image: legleux/clio_tests
  dependencies:
    - build-clio
  script:
    - ls -l
    - ./test_clio.sh



# package-clio:
#   stage: package
#   script:
#     - ./package_clio.sh
