stages:
 - build
 - test
 - package
#  - deploy

build-clio:
  stage: build
  script:
    - ./build_clio.sh

test-clio:
  stage: test
  script:
    - ./test_clio.sh


package-clio:
  stage: package
  script:
    - ./package_clio.sh
