stages:
 - build
#  - test
#  - package
#  - deploy

build-clio:
  stage: build
  image: legleux/clio_builder
  script:
  - |
    ls -lh


# test-clio:
#   stage: test
#   script:
#     - ./test_clio.sh


# package-clio:
#   stage: package
#   script:
#     - ./package_clio.sh
