stages:
 - build
 - test
 - package
 - deploy

build-clio:
  stage: build
  image: legleux/clio_builder
  script: ./build_clio.sh
  artifacts:
    paths:
      - clio_src/build/
      - clio_src/CMakeLists.txt
      # - clio_src/build/CPackSourceConfig.cmake
      # - clio_src/build/cmake_install.cmake
      # - clio_src/build/clio.service
      # - clio_src/build/debian
      # - clio_src/build/debian/postinst
      # - clio_src/build/install-config.json
      # - clio_src/build/clio_server
      # - clio_src/build/clio_tests
      # - clio_src/build/CPackConfig.cmake
  tags:
    - 4xlarge

test-clio:
  stage: test
  image: legleux/clio_tests
  dependencies:
    - build-clio
  script:
    - ./test_clio.sh

upload-package:
  stage: deploy
  dependencies:
    - build-clio
    - test-clio
  script: ["./upload_to_art.sh clio_src/build/Packages/*.deb"]
