# include(InstallRequiredSystemLibraries)

# set(CPACK_PACKAGING_INSTALL_PREFIX /opt/clio)

set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_DEBUG 1) # [ ]: REMOVE
set(CPACK_DEBIAN_PACKAGE_RELEASE 1) # version of the package
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
    ${CMAKE_SOURCE_DIR}/CMake/conffiles
    ${CMAKE_SOURCE_DIR}/CMake/postinst
    )

# NOTE: if CPACK_SET_DESTDIR is true, CPACK_PACKAGING_INSTALL_PREFIX isn't used
set(CPACK_SET_DESTDIR true) # defaults to /usr otherwise
# set(CPACK_INSTALL_PREFIX ${CPACK_PACKAGE_INSTALL_DIRECTORY})
# install(FILES conffiles DESTINATION )
set(CPACK_INSTALL_PREFIX /opt/clio) # teh only one that seems to work
# set(CMAKE_INSTALL_PREFIX CMAKKKKKKKKKKE) # this get's used if above isn't set
# set(CPACK_PACKAGING_INSTALL_PREFIX fuuuuuuuu)

set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "http://example.com")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Clio xrpld api server")
set(CPACK_PACKAGE_VENDOR "Me, myself, and I")
# set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/clio.server.txt")
# set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/Copyright.txt")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
# set(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")
# set(CPACK_DEBIAN_PACKAGE_DEPENDS fuck)
set(CPACK_STRIP_FILES "bin/clio")
set(CPACK_SOURCE_STRIP_FILES "")
set(CPACK_PACKAGE_EXECUTABLES "clio" "The clio server")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "fuck")

include(CPack)
