set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_DEBUG 1) # [ ]: REMOVE
# set(CPACK_DEBIAN_PACKAGE_RELEASE 1) # version of the package
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
    ${CMAKE_SOURCE_DIR}/CMake/conffiles
    ${CMAKE_SOURCE_DIR}/CMake/postinst
    )
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
# NOTE: if CPACK_SET_DESTDIR is true, CPACK_PACKAGING_INSTALL_PREFIX isn't used
set(CPACK_SET_DESTDIR true) # defaults to /usr otherwise
set(CPACK_INSTALL_PREFIX /opt/clio) # teh only one that seems to work
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "http://github.com/XRPLF/clio")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Ripple Labs Inc. <support@ripple.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Clio XRPL API server")
set(CPACK_PACKAGE_VENDOR "XRPLF")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
# set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.md")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_STRIP_FILES "bin/clio_server") #TODO: confirm stripped
set(CPACK_PACKAGE_EXECUTABLES "clio_server" "The Clio server")

include(CPack)
