name: Build Clio
on:
  repository_dispatch:
    types: build
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ${{ matrix.runner || 'ubuntu-20.04' }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-10.15
            name: macOS 10.15

          - runner: ubuntu-18.04
            name: Ubuntu 18.04

          - runner: ubuntu-20.04
            name: Ubuntu 20.04

          - runner: macos-11
            cxx_std: 11
            name: macOS 11

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: legleux/clio
          ref: conan-boost

      - name: Build
        run: |
          OS=${{ matrix.runner }}
          if [[ $OS =~ "ubuntu" ]]; then
            source /etc/os-release
            if [[ "${VERSION_CODENAME}" = "bionic" ]]; then
              pip3 install -U pip setuptools
              pip3 install conan
            else
              pip install conan
            fi
            export CC=$(which gcc-9)
            export CXX=$(which g++-9)
            conan profile new default --detect
            conan profile update settings.compiler.libcxx=libstdc++11 default
            conan profile update settings.compiler.cppstd=17 default

          else
            brew install conan;
            conan profile new default --detect
          fi
          conan config set general.revisions_enabled=1
          conan remote add --insert 0 legleux https://legleux.jfrog.io/artifactory/api/conan/ripple-conan
          ls -lah
          conan install . -if build
          cmake -B build
          cmake --build build --parallel $(nproc)
